/*items const*/
// export const ITEMS_HAS_ERRORED = 'ITEMS_HAS_ERRORED';
// export const ITEMS_IS_LOADING = 'ITEMS_IS_LOADING';
// export const ITEMS_FETCH_DATA_SUCCESS = 'ITEMS_FETCH_DATA_SUCCESS';

/*Location const*/
// export const LOCATIONS_HAS_ERRORED = 'LOCATIONS_HAS_ERRORED';
// export const LOCATIONS_IS_LOADING = 'LOCATIONS_IS_LOADING';
export const LOCATIONS_FETCH_DATA_SUCCESS = 'LOCATIONS_FETCH_DATA_SUCCESS';
export const LOCATIONS_SET_DATA_SUCCESS = 'LOCATIONS_SET_DATA_SUCCESS';
export const FILTER_LOCATIONS = 'LOCATIONS_SET_DATA_SUCCESS';
export const SELECT_LOCATION = 'SELECT_LOCATION';
export const UPDATE_LOCATIONS = 'UPDATE_LOCATIONS';
export const DELETE_LOCATIONS = 'DELETE_LOCATIONS';



/*Categories const*/
export const CATEGORIES_HAS_ERRORED = 'CATEGORIES_HAS_ERRORED';
export const CATEGORIES_IS_LOADING = 'CATEGORIES_IS_LOADING';
export const CATEGORIES_FETCH_DATA_SUCCESS = 'CATEGORIES_FETCH_DATA_SUCCESS';
export const CATEGORIES_SET_DATA_SUCCESS = 'CATEGORIES_SET_DATA_SUCCESS';
export const FILTER_CATEGORIES_ADD_ITEM = 'FILTER_CATEGORIES_ADD_ITEM';
export const FILTER_CATEGORIES_REMOVE_ITEM = 'FILTER_CATEGORIES_REMOVE_ITEM';
export const FETCH_FILTER_CATEGORIES = 'FETCH_FILTER_CATEGORIES';
